spring:
  config:
    import:
      classpath:secrets.yml
  jackson:
    default-property-inclusion: non_null

  jpa:
    hibernate:
      ddl-auto: update   # options: none | update | create | create-drop | validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${spring.mail.username}
    password: ${spring.mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-v5bzffnajjerms13.eu.auth0.com/

logging:
  level:
    org.hibernate.SQL: DEBUG

email:
  provider: Gmail

secret-service:
  provider: SecretManager
