spring:
  jackson:
    default-property-inclusion: non_null

  profiles:
    active: ${ACTIVE_PROFILE}

  jpa:
    hibernate:
      ddl-auto: update   # options: none | update | create | create-drop | validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: teamvaultapp@gmail.com
    password: ${GMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-v5bzffnajjerms13.eu.auth0.com/

logging:
  level:
    org.springframework.boot.context.config: DEBUG

email:
  provider: Gmail

secret-service:
  provider: SecretManager

secret-manager:
  access-key-id: ${SECRET_MANAGER_ACCESS_KEY_ID}
  secret-access-key: ${SECRET_MANAGER_SECRET_ACCESS_KEY}
  region: us-east-1
