spring:
  datasource:
    url: jdbc:h2:mem:teamvaultdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  mail:
    host: smtp.gmail.com
    port: 587
    username: teamvaultapp@gmail.com
    password: nfpe ppea wmcx arza
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-v5bzffnajjerms13.eu.auth0.com/

logging:
  level:
    org.hibernate.SQL: DEBUG

email:
    provider: Gmail
    sendGridApiKey: abc123